# Generated by Django 5.2.1 on 2025-05-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_dish_name_alter_dishtype_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dishes/"),
        ),
    ]
