# Generated by Django 5.2.1 on 2025-05-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_dish_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="image",
        ),
        migrations.AddField(
            model_name="dish",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
